services:
  quarter-next:
    container_name: quarter-next
    restart: always
    image: node:20.10.0
    ports:
      - 4000:3000

    environment:
      - PORT=3000

    volumes:
      - ./:/usr/src/quarter-next
    working_dir: /usr/src/quarter-next

    networks:
      - client-network

    # for production
    command: bash -c "yarn && yarn run build && yarn run start"

networks:
  client-network:
    driver: bridge
